services:
  paciente:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: sarah-ui-paciente
    expose:
      - "80"
    networks:
      - sarah-network
    restart: unless-stopped

networks:
  sarah-network:
    external: true